// This file was generated by Prisma, and assumes you have installed the following:
// Configuración de la CLI de Prisma (db pull, generate). La URL se toma de .env
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
